wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.9
    cli_version: 0.27.2
    framework: huggingface
    huggingface_version: 4.57.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1781407714
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 71
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 71
      3:
      - 4
      - 13
      - 16
      - 42
      4: 3.13.9
      5: 0.27.2
      6: 4.57.6
      13: linux-x86_64
    e:
      mqlet315ykdwcx0pnic77jzldlaibtpz:
        os: Linux-6.17.0-19-generic-x86_64-with-glibc2.39
        python: CPython 3.13.9
        started_at: '2026-06-14T03:28:34.281904Z'
        args:
        - --epochs
        - '1'
        - --max_steps
        - '1000'
        - --log_interval
        - '100'
        - --learning_rate
        - 5e-4
        - --hidden_size
        - '768'
        - --num_hidden_layers
        - '8'
        - --use_wandb
        program: /home/qiaohui/Project/minimind/trainer/train_pretrain.py
        code_path: trainer/train_pretrain.py
        code_path_local: train_pretrain.py
        git:
          remote_url: https://github.com/QiaohuiGao/minimind.git
          commit: 536f76ca42818f16d83f54c587f444f4206c0f81
        root: /home/qiaohui/Project/minimind/trainer
        host: RTX-Pro-6000-Workstation
        executable: /home/qiaohui/Project/minimind/.venv/bin/python
        cpu_count: 24
        cpu_count_logical: 24
        gpu_type: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
        gpu_count: 1
        disk:
          /:
            total: '1006773899264'
            used: '193876869120'
        memory:
          total: '100471738368'
        gpu_nvidia:
        - name: NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition
          memory_total: '102641958912'
          cuda_cores: 24064
          architecture: Blackwell
          uuid: GPU-e552bcb2-68d9-6186-cf78-a3e18fda64ea
        cuda_version: '13.0'
        writer_id: mqlet315ykdwcx0pnic77jzldlaibtpz
save_dir:
  desc: null
  value: ../out
save_weight:
  desc: null
  value: pretrain
epochs:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.0005
device:
  desc: null
  value: cuda:0
dtype:
  desc: null
  value: bfloat16
num_workers:
  desc: null
  value: 8
accumulation_steps:
  desc: null
  value: 8
grad_clip:
  desc: null
  value: 1.0
log_interval:
  desc: null
  value: 100
save_interval:
  desc: null
  value: 1000
max_steps:
  desc: null
  value: 1000
hidden_size:
  desc: null
  value: 768
num_hidden_layers:
  desc: null
  value: 8
max_seq_len:
  desc: null
  value: 340
use_moe:
  desc: null
  value: 0
num_attention_heads:
  desc: null
  value: 8
num_key_value_heads:
  desc: null
  value: 4
head_dim:
  desc: null
  value: 0
intermediate_size:
  desc: null
  value: 0
dropout:
  desc: null
  value: 0.0
rope_theta:
  desc: null
  value: 1000000.0
max_position_embeddings:
  desc: null
  value: 3276
num_experts:
  desc: null
  value: 4
num_experts_per_tok:
  desc: null
  value: 1
moe_intermediate_size:
  desc: null
  value: 0
router_aux_loss_coef:
  desc: null
  value: 0.0005
data_path:
  desc: null
  value: ../dataset/pretrain_t2t_mini.jsonl
from_weight:
  desc: null
  value: none
from_resume:
  desc: null
  value: 0
use_wandb:
  desc: null
  value: true
wandb_project:
  desc: null
  value: MiniMind-Pretrain
run_name:
  desc: null
  value: ''
use_compile:
  desc: null
  value: 0
